name: Build APK

on:
  push:
    branches:
      - ana
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Java kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Gradle önbellek
        uses: gradle/gradle-build-action@v2

      - name: APK derle
        run: ./gradlew assembleDebug

      - name: APK dosyasını yükle
        uses: actions/upload-artifact@v3
        with:
          name: Kurdistan3DMarabası-APK
          path: app/build/outputs/apk/debug/app-debug.apk
